version: '3'

services:
  main:
    build: .
    image: kyori/docker-mastodon-backup
    network_mode: host
    environment:
      TZ:
      CRON_TIMER:
      TOOT_DOMAIN:
      TOOT_ACCESS_TOKEN:
      PSQL_HOST:
      PSQL_PASSWORD:
      REDIS_HOST:
      REDIS_PASSWORD:
      S3_HOST:
      S3_BUCKET:
      S3_ACCESS_KEY:
      S3_ACCESS_SECRET:
