name: build

on:
  push:
    branches:
      - "*"
    tags:
      - "!*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: echo ::set-output name=version::${GITHUB_REF/refs\/heads\//}
        id: version

      - uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            kyori/docker-mastodon-backup:${{ steps.version.outputs.version }}
          cache-from: |
            kyori/docker-mastodon-backup:${{ steps.version.outputs.version }}
          cache-to: type=inline,mode=max
